### ISSUE TITLE
Spring Actuator + Prometheus + Grafana를 이용한 모니터링 환경 구축

### ISSUE THREAD

**Issue by ber01** [f-lab-edu/lo-gak-gye#25]
## APM

애플리케이션 성능 모니터링(Application Performance Monitoring, APM)

웹 애플리케이션과 서버의 성능을 실시간으로 관찰하고 분석해서, 문제가 생길 경우 빠르게 대처하고 성능을 개선하는 데에 목적

- CPU 사용률
- 메모리 사용량
- 네트워크 트래픽
- 데이터베이스 커넥션
- 기타 등등

## Spring Actuator

Spring Boot 어플리케이션의 상태와 내부 작동을 모니터링할 수 있는 기능 제공

지표(metrics), 헬스(health), 환경 설정(env) 등의 정보를 쉽게 접근할 수 있게 해준다.

## Prometheus

지표(metrics) - CPU 사용량, 쓰레드, 가비지 수집 등

수 많은 지표를 보관하기 위한 데이터베이스가 필요하다.

프로메테우스는 지표를 보관하는 데이터베이스이다.

## Grafana

그라파나는 지표를 보관하는 데이터베이스에서 데이터를 읽어와 화면을 구성하는 대시보드이다.

## 그 외

다른 APM 툴로 Scouter, VisualVM 등이 존재한다.

비슷한 기능을 하는 것 같으나 Spring Actuator가 스프링 프레임워크에서 의존성으로 제공하고 있는 만큼 호환이 더 잘될 것 같아서 선택했다.

**Comment by ber01** [comment]
## Spring Boot Actuator 의존성 추가

```groovy
implementation 'org.springframework.boot:spring-boot-starter-actuator'
```

**Comment by ber01** [comment]
## Actuator 엔드포인트 활성화

`env`, `beans` 기능을 제외한 나머지 기능 활성화

```properties
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=env,beans
```

## 톰캣 메트릭 수집

```properties
server.tomcat.mbeanregistry.enabled=true
```

**Comment by ber01** [comment]
## Actuator 배포 환경 엔드포인트 테스트

테스트 성공

<img width="1451" alt="스크린샷 2024-01-20 오후 7 22 56" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/e887a544-db7d-464d-857e-394ae3f4a4d4">

**Comment by ber01** [comment]
## 프로메테우스 의존성 추가

```groovy
runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
```

**Comment by ber01** [comment]
## 프로메테우스 배포 환경 엔드 포인트 테스트

테스트 성공

<img width="1299" alt="스크린샷 2024-01-20 오후 7 43 41" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/cc45e328-304c-4cd9-b33a-932fd10edf8a">

**Comment by ber01** [comment]
## 프로메테우스 설정

### prometheus.yml

기본 설정 파일

```yml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```

스프링 액츄에이터 설정을 추가한다.

```yml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  # actuator 
  - job_name: "actuator"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8080"]
```

이제 이걸 도커 파일로 만든 다음 EC2에 실행만 시켜주면 된다. 어떻게 하지?

**Comment by ber01** [comment]
## 일단 해보기

### 설정 파일 저장

EC2 인스턴스에 접근하여 위 설정 파일을 `prometheus.yml`로 저장해 둔다.

### INSTALLATION

- [Using Docker](https://prometheus.io/docs/prometheus/latest/installation/#using-docker)에 있는 대로 따라한다.

기본형

```
docker run \
    -p 9090:9090 \
    -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus
```

실행한 명령어

```
docker run \
    -p 9090:9090 \
    -v /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus
```

뭔가 실행이 됐다.

<img width="1522" alt="스크린샷 2024-01-20 오후 8 42 23" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/f65c605d-895b-4cea-809e-5df7ec777a39">

기본 포트가 9090 이므로 보안 그룹의 인바운드 규칙의 9090 포트를 허용한 뒤 접속 테스트를 해본다.

## 접속 테스트

프로메테우스 접속 성공

<img width="1624" alt="스크린샷 2024-01-20 오후 8 45 57" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/4da2684a-e6e1-4c82-841c-1f39e3f74891">

타겟의 헬스체크가 되는지 확인해 본다.

<img width="1792" alt="스크린샷 2024-01-20 오후 8 47 53" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/60349d80-358b-4953-a456-d7a858b1cdc0">

왜 오류가 날까?

**Comment by ber01** [comment]
## 포트 포워딩 문제

현재 호스트의 80 포트에 접근하면 컨테이너 내부의 8080 포트로 포트 포워딩 하고 있다.

즉, 호스트의 8080 포트는 없는데 접근하려고 하니 에러가 났던 것

`prometheus.yml` 파일의 포트를 `8080` 에서 `80` 으로 변경한 뒤, 타겟 테스트를 다시 해본다.

## 테스트 재시도

그래도 안 된다.

<img width="1498" alt="스크린샷 2024-01-20 오후 9 09 30" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/27a14d73-7324-43b3-bc7e-24304534be54">

## GET 요청 시도

그럼, 해당 URL이 GET요청이 안 되는지 테스트 해보자

```curl
curl http://localhost/actuator/prometheus
```

잘 나온다.

<img width="892" alt="스크린샷 2024-01-20 오후 9 11 52" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/dc56ee09-6e19-40db-bf70-0d6fad11f12a">

**Comment by ber01** [comment]
## 트러블 슈팅

도커는 독립적인 컨테이너 환경을 제공한다.

스프링 부트의 컨테이너 환경과 프로메테우스의 컨테이너 환경이 다르다.

프로메테우스가 스프링 부트를 못 찾는게 당연했던 것

이를 해결하려면 도커 컴포즈를 이용하여 동일한 네트워크 상으로 묶어야 될 것 같다.

**Comment by ber01** [comment]
## 문제점 파악

현재 EC2 인스턴스 구조

![minkh-페이지-39 drawio (1)](https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/1f801dd0-d616-494c-9851-1b126493a88c)

변경해야 할 EC2 인스턴스 구조

![minkh-페이지-40 drawio](https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/b9c27706-b0fd-486d-834c-d50258728753)

스프링 부트 애플리케이션, 프로메테우스, 그라파나가 동일한 네트워크 상에 존재하되, 배포시에는 스프링 부트 애플리케이션만 재시작 되어야 한다.

**Comment by ber01** [comment]
## 도커 컴포즈 작성 및 테스트

스프링 부트 애플리케이션, 즉 `ghcr.io/ber01/lo-gak-gye:latest` 을 우선 도커 컴포즈로 변경한다.

```bash
touch docker-compose.yml 
```

```yaml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    ports:
      - "80:8080"
```

배포 스크립트 변경

```sh
#!/bin/bash

# 이미지 풀
docker-compose pull app

# 기존에 실행중인 컨테이너 중지
docker-compose down app

# 이미지 실행
docker-compose up -d --no-deps app

# 사용하지 않는 컨테이너, 이미지 제거
docker container prune -f
docker image prune -a -f
```

**Comment by ber01** [comment]
## 프로메테우스 도커 컴포즈 작성 및 테스트

스프링 부트 애플리케이션이 잘 작동하는 것을 확인 했으니, 프로메테우스 관련 설정을 도커 컴포즈 파일에 추가한다.

```yaml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    ports:
      - "80:8080"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml
```

실행을 시킨다.

```bash
$ docker-compose up -d
```

프로메테우스를 확인한다.

또 실패하는데 정신이 나가버릴 것 같다.

<img width="1495" alt="스크린샷 2024-01-20 오후 11 24 58" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/3cd93beb-784e-426d-8be1-0fcf3b6da9b6">

**Comment by ber01** [comment]
## 트러블 슈팅

F-LAB 백엔드 개발자분 한테 물어봐서 나온 내용

Q : 같은 도커 컴포즈 내에 있어서 같은 네트워크 환경 같은데 왜 로컬 호스트에 접근이 안 될까요?

- 당연히 안 됩니다. 컴포즈 내 각 애플리케이션은 브릿지 네트워크로 연결되어 있습니다.
- 브릿지 네트워크는 도커 네트워크로 구성되어 있는데, 로컬 호스트에서 접근이 되지 않습니다.

그래서 어떻게 해결했냐?

```yaml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye
    ports:
      - "80:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml
```

컨테이너의 이름을 `docker-compose` 파일에 명시한 뒤, 이를 타겟에 등록했다.

```yaml
  # actuator
  - job_name: "actuator"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ["lo-gak-gye:8080"]
```

옛날에 쿠버네티스 운영할 때, 리소스 이름 그대로 긁어서 썼던 적이 있는데 비슷한 듯

드디어 헬스체크에 성공한다.

<img width="1497" alt="스크린샷 2024-01-21 오전 12 27 26" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/2eb4bd35-9a13-456c-9af8-f7b39d22ee19">

**Comment by ber01** [comment]
## 빌드 테스트

CI&CD 파이프 라인이 돌 때, 스프링 부트 애플리케이션만 재시작 되는지 테스트 해본다.

뭔가 버벅거리는거 같기는 한데, 되긴 된다.

이미지 실행 될 때는 DOWN 됐다가

<img width="1495" alt="스크린샷 2024-01-21 오전 12 14 27" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/b8352a87-1ccf-4afd-b6e1-fbc8bb2bc0ab">

다시 UP으로 바뀐다.

<img width="1493" alt="스크린샷 2024-01-21 오전 12 14 50" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/dd1ebb5b-cea3-4f75-8950-2407db0390c6">

**Comment by ber01** [comment]
## 그라파나 도커 컴포즈 추가

딱히 뭘 설정해 줘야 할지 잘 모르겠다.

기본적인 값만 추가

```yaml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye
    ports:
      - "80:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
```

EC2 인바운드 규칙 3000번 열고 테스트

## 접속 테스트

<img width="801" alt="스크린샷 2024-01-21 오전 1 06 00" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/6a838b58-5d9c-46f2-b1d5-d46c752e90e2">

**Comment by ber01** [comment]
## 그라파나 - 프로메테우스 연결

<img width="1468" alt="스크린샷 2024-01-21 오전 1 08 09" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/41d72a22-42ff-445a-9bea-67ff5e03b560">

<img width="1482" alt="스크린샷 2024-01-21 오전 1 08 48" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/cb1c181b-3c46-461b-8075-414db8df2bc6">

<img width="1487" alt="스크린샷 2024-01-21 오전 1 09 59" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/6d389863-6d1c-4211-b693-491868a01211">

<img width="1213" alt="스크린샷 2024-01-21 오전 1 10 24" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/16bae770-b406-4120-818d-4bbf6bbf1999">

**Comment by ber01** [comment]
## JVM - micrometer 연결

- [JVM (Micrometer)](https://grafana.com/grafana/dashboards/4701-jvm-micrometer/)

프리티어 사양이 너무 안좋아서 로딩이 안 된다.

**Comment by ber01** [comment]
# 볼륨 마운트 추가

데이터 소스를 생성한 뒤, 리부트 하니까 날아간다.

볼륨 마운트 설정을 추가한다.

- [Use Docker volumes (recommended)](https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#use-docker-volumes-recommended)

<img width="770" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/b9e06a07-12ef-4e8d-ac14-d89c3e56b81f">

```yml
version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
```

**Comment by ber01** [comment]
## 로컬에서 설정한 화면

이 화면을 EC2 인스턴스에도 설정하고 싶은데, 사양이 너무 안 좋아서 이 플러그인이 로딩이 안 된다.

어떠한 설정을 모니터링 할 지 고민을 좀 해봐야 할 듯

<img width="1674" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/1c962409-78f9-4811-b2f4-7d7ae99b89fd">

**Comment by ber01** [comment]
## docker-compose 변경

```yaml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye
    ports:
      - "80:8080"
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
```

`depends_on`

prometheus, grafana가 시작이 되고 스프링 부트 앱이 시작된다.

종속성을 가지는 옵션

## workflows 변경

```yaml
      # EC2에 접근하여 배포
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST_NAME }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user
            docker-compose pull app
            docker-compose up -d app
            docker image prune -a -f
```

이렇게 변경하니까, CI&CD 파이프라인이 돌 때, 스프링 부트 앱만 재실행 된다.

**Comment by ber01** [comment]
## 결론

`t2.micro` 인스턴스 사양이 너무 안 좋아서 스프링 부트 앱 + 프로메테우스 + 그라파나 3개의 서버를 띄우는 것이 불가능하다.

간단한 CPU 사용량 + 하드디스크 사용량 지표의 대시보드를 불러오는데 EC2 인스턴스가 먹통이 된다.

다른 APM 툴 Scouter 혹은 Visual VM을 적용할 방법을 찾아보던 지 해야할 듯(그런데 나머지 두 개라고 별 반 다를까 싶다.)

## 도커 컴포즈 변경

```yml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye
    ports:
      - "80:8080"
```
