### ISSUE TITLE
배포가 안 되는 문제

### ISSUE THREAD

**Issue by ber01** [f-lab-edu/lo-gak-gye#28]
배포가 안 된다.

<img width="1124" alt="스크린샷 2024-01-21 오전 2 57 21" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/9c34832f-7aaa-4d8d-95a1-73bc7c0ca7cc">

**Comment by ber01** [comment]
docker-compose로 변경에 따른 배포 방식에 문제가 있었다.

workflows 변경으로 해결

```yaml
      # EC2에 접근하여 배포
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST_NAME }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user
            docker-compose pull app
            docker-compose up -d app
            docker image prune -a -f
```
