### ISSUE TITLE
로드밸런서 설치

### ISSUE THREAD

**Issue by ber01** [f-lab-edu/lo-gak-gye#34]
## 목표

- 로드밸런서(Nginx)를 설치한다.
- 로드밸런서 작동을 확인한다.

스프링 부트 애플리케이션을 실행하면 기본 포트가 8080 으로 실행된다.

HTTP 통신 기본 포트는 80이기에 현재 EC2 인스턴스 내에서 포트 포워딩을 `80:8080`으로 하고있다.

이를 로드밸런서를 이용하여 개선한다.

**Comment by ber01** [comment]
## 도커 컴포즈 수정

HTTP 기본 포트 80일 경우 8080으로 포워딩 하도록 설정해뒀다.

이제 8080으로 변경해 두고, 로드밸런서가 80 포트 요청을 받으면 8080 포트로 요청을 보내도록 수정한다.

### as-is

```yaml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye
    ports:
      - "80:8080"
```

### to-be

```yaml
version: '3.8'

services:
  app:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye
    ports:
      - "8080:8080"
```

**Comment by ber01** [comment]
## Nginx 설치 및 테스트

### 패키지 저장소 업데이트

```
sudo dnf update -y
```

### Nginx 설치

```
sudo dnf install nginx -y
```

### Nginx 서비스 시작

```
sudo systemctl start nginx
```

### Nginx 설치 확인

```
sudo systemctl status nginx
```

<img width="661" alt="스크린샷 2024-01-29 오후 8 57 08" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/6740f66a-0ea3-4d41-be15-4ff842bd1144">

### 재부팅 시 Nginx 활성화

```
sudo systemctl enable nginx
```

### 접속 테스트

<img width="1624" alt="스크린샷 2024-01-29 오후 9 00 38" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/3d86674e-6d07-4718-858f-2c24dace9aac">

## Reference

- [How to install nginx in Amazon Linux 2023](https://awswithatiq.com/how-to-install-nginx-in-amazon-linux-2023/)

**Comment by ber01** [comment]
## Nginx 설정 파일 확인

### 버전 확인

```
nginx -v
```

<img width="282" alt="스크린샷 2024-01-29 오후 9 09 28" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/1562be29-5415-47fe-ac4f-451dbec389d7">

### 설정 파일 확인

버전마다 다른 것 같지만, 1.24.0 버전의 설정 파일 위치는 `/etc/nginx/nginx.conf` 인 것 같다.

<img width="1018" alt="스크린샷 2024-01-29 오후 9 11 12" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/4d12a0a0-5194-40be-80e0-8de353b39387">

**Comment by ber01** [comment]
## 리버스 프록시 설정

### 리버스 프록시란?

실제 서비스를 처리하는 WAS 앞 단에 위치하여, WAS에 직접 요청하는 것이 아닌 리버스 프록시를 통해 요청하게 된다.

로드 밸런싱, 보안 등의 이점을 누릴 수 있게 됨

### 일단 해보기

`server` 블록에서 `location / ` 블록을 추가한 뒤 아래와 같이 작성하면 된다고 한다.

```
server {

    location / {
        proxy_pass http://localhost:8080; 
    }

}        
```

location 블록에서 `/` 는 경로임 들어오는 모든 경로를 처리한다는 소리

`/abc` 로 설정하면, `/abc`에 해당하는 요청만 `localhost:8080` 으로 라우팅 시킬 수도 있음

## Nginx 설정 확인

```
sudo nginx -t
```

<img width="471" alt="스크린샷 2024-01-29 오후 10 01 58" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/b6b2eb19-82b5-4eea-a68c-edf8f91030ac">

별 문제 없는 것 같다.

## Nginx 재실행

```
sudo systemctl restart nginx 
```

**Comment by ber01** [comment]
## API 테스트

라우팅이 똑바로 된다.

<img width="1335" alt="스크린샷 2024-01-29 오후 10 03 28" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/f4a330db-46c4-41a5-8969-afebd7541dc4">

**Comment by ber01** [comment]
## 의문점

- `server_name`
- `proxy_set_header`

`proxy_set_header` 검색해 보니 이거 계속 쓰던데 이 것들은 뭐하는 옵션일까

```
server {
    listen 80;
    listen [::]:80;

    server_name _; 

    location / {
        proxy_pass http://localhost:8080;  # 스프링 부트 애플리케이션이 리스닝하는 주소
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by ber01** [comment]
## proxy_set_header

클라이언트가 프록시 서버를 거치게 되면, 백엔드 서버는 프록시 서버의 정보를 받게 된다.

즉, 클라이언트의 정보를 상실하게 되는데, 이 때 해당 옵션들을 사용하면 클라이언트의 정보도 수집이 가능하다.

- `Host $host` : 클라이언트 요청에서 사용된 호스트명을 백엔드 서버로 전달

- `X-Real-IP $remote_addr` : 클라이언트의 실제 IP 주소를 백엔드 서버에 전달

- `X-Forwarded-For $proxy_add_x_forwarded_for` : 원본 요청의 IP 주소와 프록시 체인을 통해 요청이 전달된 모든 서버의 IP 주소 포함

- `X-Forwarded-Proto $scheme` : 클라이언트가 요청을 시작할 때 사용한 프로토콜(예: http 또는 https)을 백엔드 서버로 전달

백엔드 서버가 클라이언트 헤더의 정보를 가지고 무언가 조작할 일이 있을 때, 이 정보를 넘겨주면 된다.

**Comment by ber01** [comment]
## server-name

예를 들어보자 `minkh.me` 라는 도메인이 있다.

기본적으로 동적으로 작동하지만 해당 웹 사이트를 소개하는 페이지는 정적이라고 가정하고 해당 페이지는 정적 웹 사이트다.

그러면 굳이 WAS에 부하를 줄 필요가 없다.

## 1번 정적으로 리다이렉트

```
server {
    listen 80;
    server_name info.minkh.me; 

    location / {
        root /var/www/info;
        index index.html index.htm;
    }
}
```

## 2번 WAS로 리다이렉트

```
server {
    listen 80;
    server_name *.minkh.me; 

    location / {
        proxy_pass http://localhost:8080;
    }
}
```

이외에도 다른 도메인에 대해 여러가지 처리를 할 수 있지만 이런식으로 처리하면 좋을듯 하다.

많은 응용을 해볼 수 있을듯

**Comment by ber01** [comment]
## 서버 2개 띄워보기

로드 밸런서를 설치 했으므로 서버를 2개 띄워본다.

### 도커 컴포즈 수정

8081, 8082 2개의 포트를 노출시킨다.

```yaml
version: '3.8'

services:
  app1:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye-app1
    ports:
      - "8081:8080"

  app2:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye-app2
    ports:
      - "8082:8080"
```

### Nginx 설정 파일 수정

`upstream` 지시어를 이용한다.

- 여러 서버들을 하나의 그룹으로 묶어 로드밸런싱을 위한 서버 풀(Server Pool)을 정의하는 데 사용
- Nginx에 의해 트래픽이 분산되어 처리될 대상 서버들의 집합

기본형은 아래와 같다.

```
upstream [그룹 이름] {
    server [서버 주소1];
    server [서버 주소2];
    ...
}
```

```bash
sudo vi /etc/nginx/nginx.conf
```

이렇게 정의한다.

```
upstream backend {
    server localhost:8081;
    server localhost:8082;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
    }
}
```

### 설정 확인

```
sudo nginx -t
```

### 재실행

```
sudo systemctl restart nginx 
```

**Comment by ber01** [comment]
## 오류

아래의 명령어를 실행시키니 CPU 사용률이 오른다.

```
docker-compose up -d
```

뭐가 문제인 걸까? 

WAS 한 대를 실행시켰을 때, CPU를 2%도 점유하지 않았는데 한 대를 더 실행 시킨다고 문제가 생길 것 같지는 않은데..

<img width="1426" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/d39f7c14-559e-4973-8bae-73ae058161ac">

**Comment by ber01** [comment]
## 메모리 스왑

뭐라도 성능이 좋게 하면 되려나 싶어서 메모리 스왑 진행

1GiB → 2GiB로 늘린다.

참고 자료에서 설명은 32로 하는데, 16으로 진행했음

```
$ sudo dd if=/dev/zero of=/swapfile bs=128M count=16
```

## Reference

- [스왑 파일을 사용하여 Amazon EC2 인스턴스에서 스왑 공간으로 사용할 메모리를 할당하는 방법은 무엇입니까?](https://repost.aws/ko/knowledge-center/ec2-memory-swap-file)

**Comment by ber01** [comment]
## 서버 2개 테스트

CPU 사용량을 보니까 뭔가 일시적 오류였던 것 같음

서버 2개가 제대로 라우팅 되는지 로그를 보자

현재 로컬 환경에서 `/actuator/prometheus` 엔드 포인트로 지표를 수집하고 있음

15초 마다 데이터를 수집하고 있으므로 로그에 15초마다 찍혀야 정상인데,

현재 서버가 2개이므로 Nginx가 app1에 1번, app2에 1번씩 요청을 보낸다.

따라서 서버 1개에 30초마다 로그가 찍히는 것을 볼 수 있다.

<img width="1365" alt="스크린샷 2024-01-30 오전 12 53 51" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/42ebaa64-dc4a-4a80-bad7-4a2b8a2a8a66">

즉 트래픽 분산이 잘 되고 있음.

**Comment by ber01** [comment]
## 구글 로그인이 안 되는 문제

```
Redirecting to https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=[CLIENT_ID]&scope=profile%20email&state=[STATE]&redirect_uri=http://backend/login/oauth2/code/google
```

이거 뭔가 이상하다. redirect_uri 에서 `backend`로 표시된다.

```
redirect_uri=http://backend/login/oauth2/code/google
```

의심이 되는건 Nginx 에서 `upstream`에 `backend`로 해놓은 것

이걸 우선 `checkBackend`로 변경하여 체크해본다.

```
Redirecting to https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=[CLIENT_ID]&scope=profile%20email&state=[STATE]&redirect_uri=http://checkBackend/login/oauth2/code/google
```

```
redirect_uri=http://checkBackend/login/oauth2/code/google
```

맞았다. 

이 옵션을 활성화 해본다.

> ## proxy_set_header
> 클라이언트가 프록시 서버를 거치게 되면, 백엔드 서버는 프록시 서버의 정보를 받게 된다.
> 
> 즉, 클라이언트의 정보를 상실하게 되는데, 이 때 해당 옵션들을 사용하면 클라이언트의 정보도 수집이 가능하다.
> 
> * `Host $host` : 클라이언트 요청에서 사용된 호스트명을 백엔드 서버로 전달
> * `X-Real-IP $remote_addr` : 클라이언트의 실제 IP 주소를 백엔드 서버에 전달
> * `X-Forwarded-For $proxy_add_x_forwarded_for` : 원본 요청의 IP 주소와 프록시 체인을 통해 요청이 전달된 모든 서버의 IP 주소 포함
> * `X-Forwarded-Proto $scheme` : 클라이언트가 요청을 시작할 때 사용한 프로토콜(예: http 또는 https)을 백엔드 서버로 전달
> 
> 백엔드 서버가 클라이언트 헤더의 정보를 가지고 무언가 조작할 일이 있을 때, 이 정보를 넘겨주면 된다.

**Comment by ber01** [comment]
## 설정 변경

### proxy_set_header 옵션 활성화

<img width="513" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/7d48453f-065e-4eee-a172-a331a7aff6ca">

### 확인 및 재실행

```
sudo nginx -t
```

```
sudo systemctl restart nginx
```

### 로그 확인

정상적으로 오는데 에러가 난다.

```
redirect_uri=http://ec2-XX-XXX-XXX-XX.ap-northeast-2.compute.amazonaws.com/login/oauth2/code/google
```

아무래도, 서버가 2개라서 1개의 서버에서 인증 객체가 생성이 된 다음 다른 로드 밸런서가 다음 서버로 요청을 보내니까 그 요청이 되지 않는게 아닐까 하는 의심이 든다.

**Comment by ber01** [comment]
## 서버를 1개로 변경해서 테스트

서버를 1개로 변경하여 서버가 2개여서 인증 객체가 문제인지 로그인이 문제인지 파악한다.

### 변경전

```yaml
version: '3.8'

services:
  app1:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye-app1
    ports:
      - "8081:8080"

  app2:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye-app2
    ports:
      - "8082:8080"
```

````
    upstream backend {
        server localhost:8081;
        server localhost:8082;
    }
````

### 변경 후

```yaml
version: '3.8'

services:
  app1:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye-app1
    ports:
      - "8081:8080"
```

```
    upstream backend {
        server localhost:8081;
    }
```

### 테스트

서버가 2개여서 발생하는 문제가 맞는 것 같다.

![image](https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/b812ddcc-c54b-4e74-ba77-a3f135dd49fe)

### 트러블 슈팅 후기

`proxy_set_header` 정리 안 하고 + 시큐리티 관련 로그 안 찍었으면 이거 평생 못 찾았을 것 같다;;;
