### ISSUE TITLE
캐싱 기능 추가

### ISSUE THREAD

**Issue by ber01** [f-lab-edu/lo-gak-gye#41]
## 목표

- `POST /engravings/calc` 에 캐싱 기능을 추가한다.

API의 특성상 동일한 요청을 보낼 가능성이 높다.

1분안에 동일한 요청을 보낼 시 캐싱된 데이터로 응답하도록 한다.

## 기대 효과

- 데이터베이스를 조회하지 않아도 됨
- 서버에서 연산을 하지 않아도 됨

**Comment by ber01** [comment]
## Redis 의존성 추가

```groovy
implementation 'org.springframework.boot:spring-boot-starter-data-redis'
```

## Redis 다운로드 및 실행

- 로컬환경

```
docker pull redis
```

```
docker run -d -p 6379:6379 --name redis redis
```

## application.properteis 추가

```properties
spring.cache.type=redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
```

**Comment by ber01** [comment]
## RedisConfig 설정

```java
@EnableCaching
@Configuration
public class RedisConfig {

    @Value("${spring.data.redis.host}")
    private String host;

    @Value("${spring.data.redis.port}")
    private int port;

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        return new LettuceConnectionFactory(host, port);
    }

    @Bean
    public RedisTemplate<Object, Object> redisTemplate() {
        RedisTemplate<Object, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory());
        redisTemplate.setKeySerializer(new GenericJackson2JsonRedisSerializer());
        redisTemplate.setValueSerializer(new GenericJackson2JsonRedisSerializer());
        return redisTemplate;
    }
}
```

## 고려할 점

일반적으로 Redis의 키는 문자열이다.

나는 동일한 `request`가 왔을 때, 동일한 `response`를 반환해 주고 싶어서 `json` 자체를 키로 쓰고 싶었는데, 권장하는 방식이 아니라고 한다.

~~일단 돌아가는지 테스트한 다음 이 토픽에 대해 다뤄본다.~~

`toString()`을 호출해서 키로 저장시킨다.

**Comment by ber01** [comment]
## 오류 발생

```
org.springframework.data.redis.serializer.SerializationException: Could not read JSON:Unexpected token (START_OBJECT)
```

## 키의 직렬화 방식

- GenericJackson2JsonRedisSerializer

`GenericJackson2JsonRedisSerializer`을 사용하면 변환할 클래스를 명시적으로 지정해 주지 않아도 되지만 객체의 클래스 타입을 키에 포함시킨다.

<img width="1438" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/39c3a4b2-51c3-4ac4-91fd-5f7484d35530">

키를 확인해 보면, `@class`로 들어가 있다.

## Reference

- [1](https://mongsil-jeong.tistory.com/25)
- [2](https://bcp0109.tistory.com/384)

**Comment by ber01** [comment]
## 해결 방법

```java
@Bean
public RedisTemplate<String, String> redisTemplate() {
    RedisTemplate<String, String> redisTemplate = new RedisTemplate<>();
    redisTemplate.setConnectionFactory(redisConnectionFactory());
    redisTemplate.setKeySerializer(new StringRedisSerializer());
    redisTemplate.setValueSerializer(new StringRedisSerializer());
    return redisTemplate;
}
```

키, 값 전부 String으로 저장시킨 다음 `ObjectMapper`로 변환한다.

**Comment by ber01** [comment]
## 테스트

- `POST /engravings/calc`

<img width="1790" alt="스크린샷 2024-02-11 오후 3 41 39" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/c5d79d0e-3e2b-4483-bb7d-1cca9331c0ff">

맨 처음 요청은 데이터베이스를 조회한다.

두 번째, 세 번째 요청은 데이터베이스를 조회하지 않는다.

<img width="1087" alt="스크린샷 2024-02-11 오후 3 43 40" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/23386d40-5378-477c-8e93-fbe58c340db8">

맨 처음 요청은 57ms 가 걸렸다.

<img width="1087" alt="스크린샷 2024-02-11 오후 3 44 08" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/5172a602-031f-4b67-bcd3-7b4a8ae07c7b">

이 후 요청은 15ms 가 걸렸다.

**Comment by ber01** [comment]
## 배포 환경 레디스 추가

```yaml
version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: lo-gak-gye-redis
    ports:
      - "6379:6379"

  app1:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye-app1
    ports:
      - "8081:8080"
    depends_on:
      - redis

  app2:
    image: ghcr.io/ber01/lo-gak-gye:latest
    container_name: lo-gak-gye-app2
    ports:
      - "8082:8080"
    depends_on:
      - redis
```

## workflows 수정

`app1`, `app2`만 재시작 하도록 변경

```yaml
docker-compose pull
docker-compose up -d app1 app2
docker image prune -a -f
```
